# Generated by Django 2.1.7 on 2019-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noted_by', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete='models.PROTECT', related_name='notes', to='login.Patient')),
                ('users', models.ManyToManyField(related_name='faves', to='login.Patient')),
            ],
        ),
    ]
